#ifndef PINDEFS_H
#define PINDEFS_H

#define ROTA_PORT PORTC
#define ROTA_PIN 0
#define ROTB_PORT PORTC
#define ROTB_PIN 1
#define FPS_RX_PORT PORTC
#define FPS_RX_PIN 2
#define FPS_TX_PORT PORTC
#define FPS_TX_PIN 3
#define MD1_SPI_PORT PORTC
#define MD1_SPI_PIN 4
#define BUZZ_PORT PORTC
#define BUZZ_PIN 5

#define MD2_SPI_PORT PORTD
#define MD2_SPI_PIN 0
#define PL_BAR_PORT PORTD
#define PL_BAR_PIN 1
#define SOLENOID_FORWARD_PORT PORTD
#define SOLENOID_FORWARD_PIN 2
#define SOLENOID_REVERSE_PORT PORTD
#define SOLENOID_REVERSE_PIN 3
#define DC_PORT PORTD
#define DC_PIN 4
#define MD3_SPI_PORT PORTD
#define MD3_SPI_PIN 5
#define SHIFTREG_Q_PORT PORTD
#define SHIFTREG_Q_PIN 6
#define ROT_SWITCH_PORT PORTD
#define ROT_SWITCH_PIN 7

#define MD_ENABLE_PORT PORTB
#define MD_ENABLE_PIN 0
#define SD_SPI_PORT PORTB
#define SD_SPI_PIN 1
#define LCD_SPI_PORT PORTB
#define LCD_SPI_PIN 2
#define MOSI_PORT PORTB
#define MOSI_PIN 3
#define MISO_PORT PORTB
#define MISO_PIN 4
#define SCK_PORT PORTB
#define SCK_PIN 5
#define SHCP_PORT PORTB
#define SHCP_PIN 6
#define STCP_PORT PORTB
#define STCP_PIN 7


#endif